### ISSUE TITLE
How to move tabs to the left

### ISSUE THREAD

**Issue by osenvosem** [edkolev/tmuxline.vim#112]
I want to move tabs from the center to the left in custom preset. How can I do it?

**Comment by fr-ser** [comment]
You should use the `win` and `cwin` keys and align them left. For example

```
let g:tmuxline_preset = {
      \'a'    : '#S',
      \'win'  : '#I|#W',
      \'cwin' : '#I|#W',
      \'x'    : '%a',
      \'y'    : '#W %R',
      \'z'    : '#H',
      \'options': {
        \'status-justify': 'left'}
      \}
```

**Comment by mroavi** [comment]
It took me an hour to get here. It would be nice if you include this in the readme.
