### ISSUE TITLE
tmux Version Requirements

### ISSUE THREAD

**Issue by damonkelley** [edkolev/tmuxline.vim#23]
It might be worth documenting the tmux version requirement. I hadn't updated homebrew on my machine in a while. I ended up with tmux 1.8, and got a handful of error messages after sourcing the snapshot I created. 

In addition to the errors, the result status line looked like this....
![screen shot 2014-06-21 at 12 03 49 am](https://cloud.githubusercontent.com/assets/4121849/3347877/9edb2efe-f901-11e3-9744-7b9b227844a1.png)

After I realized that there was a newer version of tmux available, I updated it and everything was dandy :+1: 

BTW, it is a nifty plugin, and saved me a lot of time getting it just right. Thanks for doing what you do.

**Comment by Oddegamra** [comment]
@edkolev: Starting with tmux 2.9, the xxx-style options are the only accepted values for tmux, as support for the deprecated values has been dropped (see https://raw.githubusercontent.com/tmux/tmux/2.9/CHANGES):

> * The individual -fg, -bg and -attr options have been removed; they
>   were superseded by -style options in tmux 1.9.

**Comment by edkolev** [comment]
Thanks for letting me know!
