### ISSUE TITLE
Change tmux colors based on vim modes

### ISSUE THREAD

**Issue by giggio** [edkolev/tmuxline.vim#24]
Right now when I enter visual mode or insert mode my airline theme changes my vim statusline color. But tmux color is not changing. This issue is to watch changes in vim (or maybe airline) and propagate them to tmux.

**Comment by JordanTHarris** [comment]
Is there no way to change it in Replace mode too? There isn't a theme, but you can initialize it to have replace colors with vim-airline in your vimrc. I just don't know how you could make it change to those colors on the fly. Here's what the README for vim-airline says:

    * configure which mode colors should be used in tmux statusline >
      let airline#extensions#tmuxline#color_template = 'normal' (default)
      let airline#extensions#tmuxline#color_template = 'insert'
      let airline#extensions#tmuxline#color_template = 'visual'
      let airline#extensions#tmuxline#color_template = 'replace'

By the way, thanks for that snippet @giggio. I couldn't figure this out for the life of me. I'm hoping there is a way to make it work for insert mode too though.

**Comment by JordanTHarris** [comment]
Actually, I found a way to use Replace mode by making a simple change to @giggio's script above and one of the airline themes included with tmuxline. I literally replaced two words in the theme file. It might be nice to have that included with tmuxline. Here's the code:

```Vim
    " change status of Tmuxline when Vim mode changes
    if exists('$TMUX')
	function! AddTmuxlineStatus()
	    if exists(':Tmuxline')
		augroup airline_tmuxline
		    au!
		    au InsertEnter * call SetInsert()
		    au InsertChange * call SetInsert()
		    autocmd InsertLeave * call SetNormal()
		    vnoremap <silent> <expr> <SID>SetVisual SetVisual()
		    nnoremap <silent> <script> v v<SID>SetVisual
		    nnoremap <silent> <script> V V<SID>SetVisual
		    nnoremap <silent> <script> <C-v> <C-v><SID>SetVisual
		    autocmd CursorHold * call SetNormal()
		augroup END
	    endif
	endfunction
	function! SetInsert()
	    if v:insertmode == 'i'
	        Tmuxline airline_insert
	    else
	        Tmuxline airline_replace
	    endif
	endfunction
	function! SetVisual()
	    set updatetime=0
	    Tmuxline airline_visual
	    return ''
	endfunction
	function! SetNormal()
	    set updatetime=4000
	    Tmuxline airline
	endfunction
	au VimEnter * :call AddTmuxlineStatus()
    endif   " exists('$TMUX')
```

Then I created a file called **airline_replace.vim** in the following directory: **.../tmuxline.vim/autoload/tmuxline/themes**. The contents of this file are as follows:

```vim
    fun! tmuxline#themes#airline_replace#get() abort
      if !has_key(g:, 'airline_theme')
	throw "tmuxline: Can't load theme from airline, g:airline_theme isn't defined. Is airline loaded?"
      endif
      if !has_key(g:, 'airline#themes#' . g:airline_theme . '#palette')
	throw "tmuxline: Can't load theme from airline, 'g:airline#themes#" . g:airline_theme . "#palette' isn't defined. Is airline loaded?"
      endif
    
      let mode = 'replace'
      let mode_palette = g:airline#themes#{g:airline_theme}#palette[mode]
      return tmuxline#util#create_theme_from_airline(mode_palette)
    endfun
```

**Comment by jdurand** [comment]
@giggio (and @JordanTHarris) thanks for the script. The only **minor** issue I was seeing was that when switching to visual mode Vim's status bar didn't update until I actually started selecting :

![screen recording 2018-12-14 at 11 12 am](https://user-images.githubusercontent.com/1762666/50014286-8d412e00-ff91-11e8-8fee-22ab30f7e958.gif)

I didn't dig enough to understand why, but it has something to do with that `return ''` because without it the mode switch is instant... but it's also what prevented the cursor from annoyingly jumping to the beginning of the line after switching to visual mode.

![screen recording 2018-12-14 at 11 13 am](https://user-images.githubusercontent.com/1762666/50014296-93cfa580-ff91-11e8-95f1-0bb0be8ef024.gif)

Using `return 'lh'` fixes this :

```vim
function! SetVisual()
    set updatetime=0
    Tmuxline airline_visual
    return 'lh'
endfunction
```

![screen recording 2018-12-14 at 11 13 am](https://user-images.githubusercontent.com/1762666/50015170-deeab800-ff93-11e8-9c66-164d594a4f5f.gif)

**Comment by phaalonso** [comment]
Any way to do this with gruvbox? Using the extension the tmux is changed properly, but it won't change when trading of vim modes. I can't find the equivalent of airline_insert to gruvbox.

**Comment by g6ai** [comment]
@jdurand Similar solution is mentioned in the comment in this [SO answer](https://stackoverflow.com/a/15587011/10039621):

> If you add that `return ''` call as I suggested, then before the color updates a key needs to be pressed. This is a little hacky, but at the end of each `nnoremap` line you can just add `<left><right>`.
