### ISSUE TITLE
How to remove extra whitespace in tmuxline?

### ISSUE THREAD

**Issue by firedev** [edkolev/tmuxline.vim#28]
In relation to this ticket https://github.com/bling/vim-airline/issues/617 how do I remove extra whitespace in tmuxline as well?

![](http://cl.ly/Xypt/Image%202014-10-10%20at%207.53.59%20pm.png)

Here is what I have in `.vimrc` now but it's not enough it seems:

```
let g:tmuxline_separators = {
  \ 'left' : '',
  \ 'left_alt': '',
  \ 'right' : '',
  \ 'right_alt' : '',
  \ 'space' : ' '}
```

**Comment by michaelfresco** [comment]
I just wanna report than in 2018 the minimal theme gives exactly the result I wanted.

![screen shot 2018-03-11 at 4 24 41 pm](https://user-images.githubusercontent.com/15065392/37255157-ce19c424-2548-11e8-906a-888e1dedf3e1.png)

`let g:tmuxline_preset = 'minimal`

Thank you @firedev
