### ISSUE TITLE
I installed the plugin using pathogen but vim doesn't recognize ":Tmuxline" as a command.

### ISSUE THREAD

**Issue by BeekeeperAlex** [edkolev/tmuxline.vim#33]
I'm not exactly sure what I'm doing wrong, but the plugin doesn't appear to be making the `:Tmuxline` command available to Vim.

![](http://i.imgur.com/VfaGum9.gif)

Any idea what I'm doing wrong here? I'm using lightline rather than airline. Here is a list of [all the plugins I'm using](https://github.com/chevex/.vim/tree/master/bundle) as well.

**Comment by 0xFN89** [comment]
Hi , I installed tmuxline and opened vim inside tmux but it still shows the same error :should be executed under a tmux session .
