### ISSUE TITLE
It is possible to enable airline/tmuxline status bar during start of tmux?

### ISSUE THREAD

**Issue by egel** [edkolev/tmuxline.vim#44]
I wondering that is even possible to start automatically airline/tmuxline status bar when I run tmux? 
Currently I have to run vim to enable (overwrite) default tmux status bar. 
Probably I miss something in my [.tmux.conf](https://github.com/egel/dotfiles/blob/master/.tmux.conf) or [.vimrc](https://github.com/egel/dotfiles/blob/master/.vimrc) ... but don't know what it is.

**Comment by egel** [comment]
Ok, my bad... I already solved my problem ;)

**Comment by simonsmith** [comment]
@egel How did you solve this?

**Comment by simonsmith** [comment]
Solved it. Had to create  a snapshot and source it in my `.tmux.conf` - https://github.com/edkolev/tmuxline.vim#usage

**Comment by buddhablessed** [comment]
In case this helps...

In .vimrc file:
" for tmuxline + vim-airline integration
let g:airline#extensions#tmuxline#enabled = 1
" start tmuxline even without vim running
let airline#extensions#tmuxline#snapshot_file = "~/.tmux-status.conf"

In .tmux.conf:
# goes with vim-airline integration, starts tmuxline even without vim
if-shell "test -f ~/.tmux-status.conf" "source ~/.tmux-status.conf"
