### ISSUE TITLE
use github release function

### ISSUE THREAD

**Issue by shibumi** [edkolev/tmuxline.vim#69]
Hello,
I would like to package your project for Arch Linux. Could you please use the release function in github?

![..](https://paste.archlinux.de/r8E6/)

**Comment by rosshadden** [comment]
@shibumi That's kind of weird to add a vim plugin to AUR.  Out of curiosity, why aren't you using a vim package manager that installs from git(hub)?

**Comment by shibumi** [comment]
@rosshadden
Its Simple. When I install software via third party installer the files on my system will not be tracked by my distribution package management. So it's possible that I forget to update, remove files when I install something with my main package manager and so on. Moreover I dont like to have to every stuff an own package manager. (Vim is not the only one.. there is also npm, ruby gems, pip, etc etc..). That's the reason why I want to package it. This way user can easily search for it in the terminal and install it with one eye blink

**Comment by kevinkjt2000** [comment]
vim plugins are installed typically under the home directory of a user.  Home directory files do not make much sense to package...

**Comment by shibumi** [comment]
@kevinkjt2000 no, many people install their vim plugins to `/usr/share/vim/vimfiles`. This makes more sense on a single user system, because you will have the same plugins with root and your working user. No need to store data twice..

**Comment by edkolev** [comment]
It's already in AUR https://aur.archlinux.org/packages/tmuxline-git/

**Comment by shibumi** [comment]
@edkolev  this is the -git version. I want to package a *stable* version

**Comment by kevinkjt2000** [comment]
@shibumi _Typically_ users do install to the home folder.  Do a couple of searches on GitHub:
https://github.com/search?utf8=%E2%9C%93&q=set+runtimepath&type=Code
https://github.com/search?utf8=%E2%9C%93&q=let+%26rtp&type=Code
https://github.com/search?utf8=%E2%9C%93&q=%22vundle%23begin%22&type=Code

And you can package a "stable" version by specifying a git revision in a PKGFILE.
https://bbs.archlinux.org/viewtopic.php?id=184386

**Comment by shibumi** [comment]
@kevinkjt2000 sorry but specifing a git revision in a PKGFILE sucks.. This is something that a developer should decide and I really don't get it. Why is it so complicated just to press on 'release' in github?!

I mean if you want to have this package in any official repository you need a stable release, maintainers will not package the `HEAD` of master or any revision..

**Comment by kevinkjt2000** [comment]
I wasn't arguing against the release button; just providing a method that works.  Copy pasting a ref, like copy pasting a release tag feels really similar to me though.

**Comment by kevinkjt2000** [comment]
@shibumi It is also possible to tag a release on a personal fork, like I just did https://github.com/kevinkjt2000/tmuxline.vim/releases/tag/v1.0

**Comment by shibumi** [comment]
@kevinkjt2000 yes I know.. but thats exactly not what I want..

**Comment by edkolev** [comment]
Will this do it? https://github.com/edkolev/tmuxline.vim/releases/tag/v1.0
