### ISSUE TITLE
Applying tmuxline theme when creating a tmux session from console ?

### ISSUE THREAD

**Issue by pingsoli** [edkolev/tmuxline.vim#95]
When I create a tmux new session, the tmuxline theme will not be applied, I must open vim first.

Any better idea ?

**Comment by gseidler** [comment]
While running vim under tmux, export your tmuxline config with `:TmuxlineSnapshot [file]`. You can later source this config file on your tmux.conf `source-file [file]`. It's all on the main page. If you change the Airline theme you need to export the tmuxline config again.

**Comment by pingsoli** [comment]
It works like a charm, thank you so much.
